# https://taskfile.dev

version: '3'

vars:
  # DOCKER_DEFAULT:
  #   sh: ./docker-containers.sh | fzf
  DOCKER_DEFAULT: dev-cycle-gear-redline-webapp-1

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  gitbranch:
    vars:
      PREFIXES: [RM, RPM, MRKT, NERD]
    cmds:
      - echo WIP note to self, pull username from git as a dynamic var

  wip:
    cmds:
      - sh ./docker-containers.sh | fzf

  logs:
    desc: Follows docker log output
    summary: |
      A stream of docker logs with `--follow`
      piped through color coding with `bat`
    aliases: [log]
    cmds:
      - cmd: docker logs --follow {{.DOCKER_DEFAULT}} |  bat --paging=never --style=plain -l log
        ignore_error: true
        interactive: true

  test:
    desc: Runs a `mix test`
    summary: |
      Runs `mix test`
      Can optionally take a test file:
      `task test -- tests/ui/ui_text.exs`
    cmds:
      - docker exec -it {{.DOCKER_DEFAULT}} mix test {{.CLI_ARGS}}

  kick:
    desc: Runs `setup.sh` and a full Docker restart
    summary: |
      Runs `/workspaces/dev-hub/setup.sh`
      then fully takes down then up's Docker containers.
      Safe to run multiple times a day if you're patient.
    cmds:
      - bash /workspaces/dev-hub/setup.sh
      - docker compose down
      - docker compose up -d

  eslint:
    desc: Runs Eslint against JavaScript files
    summary: |
      Runs ESLint against `*.js` files within the Redline Web Store.
      Supports `task eslint -- --fix` to automatically fix what is possible.
      Remember to changes after running!
    cmds:
      - docker exec -w /rz/redline/apps/redline_web_store -it {{.DOCKER_DEFAULT}} npx eslint {{.CLI_ARGS}}
